In [1]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
data_path = "/content/drive/MyDrive/Kuliah/ML/voice.csv"

df = pd.read_csv(data_path)
df.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male

In [4]:
X = df.drop(columns=["label"])
y = df["label"]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

print("Classes:", list(encoder.classes_))
print("Dataset size:", len(X))

Classes: ['female', 'male']
Dataset size: 3168

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training:", len(X_train))
print("Testing:", len(X_test))

Training: 2217
Testing: 951

In [6]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training:", len(X_train2))
print("Testing:", len(X_test2))

Training: 2534
Testing: 634

In [7]:
# Train
model_linear_70 = SVC(kernel="linear", C=1.0)
model_linear_70.fit(X_train, y_train)

SVC(kernel='linear')

In [8]:
# Test
pred_linear_70 = model_linear_70.predict(X_test)
accuracy_linear_70 = accuracy_score(y_test, pred_linear_70)

print("Linear (70:30) accuracy:", accuracy_linear_70)

Linear (70:30) accuracy: 0.9263932702418507

In [9]:
# Train
model_linear_80 = SVC(kernel="linear", C=1.0)
model_linear_80.fit(X_train2, y_train2)

SVC(kernel='linear')

In [10]:
# Test
pred_linear_80 = model_linear_80.predict(X_test2)
accuracy_linear_80 = accuracy_score(y_test2, pred_linear_80)

print("Linear (80:20) accuracy:", accuracy_linear_80)

Linear (80:20) accuracy: 0.9416403785488959

In [11]:
# Train
model_poly_70 = SVC(kernel="poly", degree=3, C=1.0)
model_poly_70.fit(X_train, y_train)

SVC(kernel='poly')

In [12]:
# Test
pred_poly_70 = model_poly_70.predict(X_test)
accuracy_poly_70 = accuracy_score(y_test, pred_poly_70)

print("Polynomial (70:30) accuracy:", accuracy_poly_70)

Polynomial (70:30) accuracy: 0.4900105152471083

In [13]:
# Train
model_poly_80 = SVC(kernel="poly", degree=3, C=1.0)
model_poly_80.fit(X_train2, y_train2)

SVC(kernel='poly')

In [14]:
# Test
pred_poly_80 = model_poly_80.predict(X_test2)
accuracy_poly_80 = accuracy_score(y_test2, pred_poly_80)

print("Polynomial (80:20) accuracy:", accuracy_poly_80)

Polynomial (80:20) accuracy: 0.48264984227129337

In [15]:
# Train
model_rbf_70 = SVC(kernel="rbf", C=1.0)
model_rbf_70.fit(X_train, y_train)

SVC()

In [16]:
# Test
pred_rbf_70 = model_rbf_70.predict(X_test)
accuracy_rbf_70 = accuracy_score(y_test, pred_rbf_70)

print("RBF (70:30) accuracy:", accuracy_rbf_70)

RBF (70:30) accuracy: 0.6624605678233438

In [17]:
# Train
model_rbf_80 = SVC(kernel="rbf", C=1.0)
model_rbf_80.fit(X_train2, y_train2)

SVC()

In [18]:
# Test
pred_rbf_80 = model_rbf_80.predict(X_test2)
accuracy_rbf_80 = accuracy_score(y_test2, pred_rbf_80)

print("RBF (80:20) accuracy:", accuracy_rbf_80)

RBF (80:20) accuracy: 0.6561514195583596

In [20]:
results = pd.DataFrame({
    "Kernel": ["Linear", "Linear", "Polynomial", "Polynomial", "RBF", "RBF"],
    "Split": ["70:30", "80:20", "70:30", "80:20", "70:30", "80:20"],
    "Accuracy": [
        accuracy_linear_70,
        accuracy_linear_80,
        accuracy_poly_70,
        accuracy_poly_80,
        accuracy_rbf_70,
        accuracy_rbf_80,
    ],
})

results

       Kernel  Split  Accuracy
0      Linear  70:30  0.926393
1      Linear  80:20  0.941640
2  Polynomial  70:30  0.490011
3  Polynomial  80:20  0.482650
4         RBF  70:30  0.662461
5         RBF  80:20  0.656151