In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
data = pd.read_csv('spam.csv', encoding='latin-1')

data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [3]:
# mengambil kolom yang diperlukan

data = data[['v1', 'v2']]

data.columns = ['label', 'message']

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.shape

(5572, 2)

In [5]:
data['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
# menentukan fitur dan label

X = data['message']
y = data['label']

In [7]:
# membagi data training dan test

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [8]:
# TUGAS 1

cv = CountVectorizer(stop_words='english')

In [9]:
# mengubah data training dan testing

X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

In [10]:
# membuat model multinomial native bayes

model_cv = MultinomialNB()

model_cv.fit(X_train_cv, y_train)

MultinomialNB()

In [11]:
# prediksi

y_pred_cv = model_cv.predict(X_test_cv)

In [12]:
# evaluasi

akurasi_cv = accuracy_score(y_test, y_pred_cv)

print('Akurasi CountVectorizer:')
print(akurasi_cv)

Akurasi CountVectorizer:
0.9838565022421525

In [13]:
print(confusion_matrix(y_test, y_pred_cv))

[[960   6]
 [ 12 137]]

In [14]:
print(classification_report(y_test, y_pred_cv))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99       966
        spam       0.96      0.92      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

Model Multinomial Naive Bayes menggunakan CountVectorizer dengan stop_words='english' menghasilkan akurasi sebesar sekitar 98,39%.

In [15]:
# TUGAS 2

# membuat tf-idf

tfidf = TfidfVectorizer(stop_words='english')

In [16]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [17]:
# membuat model multinomial naive bayes

model_tfidf = MultinomialNB()

model_tfidf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [18]:
# prediksi

y_pred_tfidf = model_tfidf.predict(X_test_tfidf)

In [19]:
# evaluasi tf-idf

akurasi_tfidf = accuracy_score(y_test, y_pred_tfidf)

print('Akurasi TF-IDF:')
print(akurasi_tfidf)

Akurasi TF-IDF:
0.968609865470852

In [20]:
print(confusion_matrix(y_test, y_pred_tfidf))

[[966   0]
 [ 35 114]]

In [21]:
print(classification_report(y_test, y_pred_tfidf))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98       966
        spam       1.00      0.77      0.87       149

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115

Model Multinomial Naive Bayes menggunakan TF-IDF dengan stop_words='english' menghasilkan akurasi sebesar sekitar 96,86%.

In [22]:
# MEMBANDINGKAN CountVectorizer dan TD-IDF

print('Akurasi CountVectorizer :',
      round(akurasi_cv * 100, 2), '%')

print('Akurasi TF-IDF          :',
      round(akurasi_tfidf * 100, 2), '%')

Akurasi CountVectorizer : 98.39 %
Akurasi TF-IDF          : 96.86 %

In [23]:
# FITUR TERBAIK

if akurasi_cv > akurasi_tfidf:
    print('Fitur terbaik adalah CountVectorizer')
elif akurasi_tfidf > akurasi_cv:
    print('Fitur terbaik adalah TF-IDF')
else:
    print('Kedua fitur memiliki akurasi yang sama')

Fitur terbaik adalah CountVectorizer